In [36]:
from  keras.wrappers.scikit_learn  import  KerasClassifier
from  sklearn.model_selection  import  GridSearchCV
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
import numpy as np
from sklearn.metrics import accuracy_score
from keras.utils import np_utils

In [2]:
from keras.datasets import mnist

In [3]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [4]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [5]:
X_train = X_train.reshape(X_train.shape[0], 784)
X_test = X_test.reshape(X_test.shape[0], 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [6]:
y_train = np_utils.to_categorical(y_train, 10)
y_test = np_utils.to_categorical(y_test, 10)

In [7]:
print (y_train.shape)
print (y_train[:10,:])

(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [8]:
input_size = 784
hidden_neurons = 100
out_size = 10

In [21]:
    def model_creator():

        model = Sequential()

        model.add(Dense(hidden_neurons, input_dim = input_size))
        model.add(Activation('sigmoid'))
        model.add(Dense(out_size, input_dim = hidden_neurons))
        model.add(Activation('softmax'))

        model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

        return model

In [10]:
seed = 2 
np.random.seed(seed)

In [11]:
model = KerasClassifier(build_fn = model_creator, verbose=2)

In [12]:
batch_size = [30 , 50 , 100 ]
epochs = [10 , 15 , 20]
param_grid = dict(batch_size=batch_size, epochs=epochs)

In [13]:
#4
grid = GridSearchCV(estimator = model, param_grid = param_grid, cv = 10, scoring = 'neg_log_loss')

In [14]:
grid.fit(X_train, y_train)


Epoch 1/10
 - 1s - loss: 0.4323 - accuracy: 0.8901
Epoch 2/10
 - 1s - loss: 0.2095 - accuracy: 0.9400
Epoch 3/10
 - 2s - loss: 0.1572 - accuracy: 0.9544
Epoch 4/10
 - 1s - loss: 0.1236 - accuracy: 0.9643
Epoch 5/10
 - 1s - loss: 0.0996 - accuracy: 0.9714
Epoch 6/10
 - 1s - loss: 0.0827 - accuracy: 0.9769
Epoch 7/10
 - 1s - loss: 0.0696 - accuracy: 0.9803
Epoch 8/10
 - 1s - loss: 0.0592 - accuracy: 0.9839
Epoch 9/10
 - 1s - loss: 0.0510 - accuracy: 0.9860
Epoch 10/10
 - 1s - loss: 0.0435 - accuracy: 0.9887
Epoch 1/10
 - 1s - loss: 0.4277 - accuracy: 0.8918
Epoch 2/10
 - 1s - loss: 0.2091 - accuracy: 0.9397
Epoch 3/10
 - 1s - loss: 0.1552 - accuracy: 0.9554
Epoch 4/10
 - 1s - loss: 0.1228 - accuracy: 0.9654
Epoch 5/10
 - 1s - loss: 0.1011 - accuracy: 0.9711
Epoch 6/10
 - 1s - loss: 0.0843 - accuracy: 0.9762
Epoch 7/10
 - 1s - loss: 0.0714 - accuracy: 0.9802
Epoch 8/10
 - 1s - loss: 0.0606 - accuracy: 0.9829
Epoch 9/10
 - 2s - loss: 0.0526 - accuracy: 0.9857
Epoch 10/10
 - 1s - loss: 0.0

Epoch 12/15
 - 2s - loss: 0.0331 - accuracy: 0.9921
Epoch 13/15
 - 2s - loss: 0.0288 - accuracy: 0.9933
Epoch 14/15
 - 2s - loss: 0.0248 - accuracy: 0.9943
Epoch 15/15
 - 2s - loss: 0.0209 - accuracy: 0.9959
Epoch 1/15
 - 2s - loss: 0.4294 - accuracy: 0.8902
Epoch 2/15
 - 2s - loss: 0.2087 - accuracy: 0.9404
Epoch 3/15
 - 2s - loss: 0.1560 - accuracy: 0.9551
Epoch 4/15
 - 2s - loss: 0.1236 - accuracy: 0.9649
Epoch 5/15
 - 2s - loss: 0.1005 - accuracy: 0.9713
Epoch 6/15
 - 2s - loss: 0.0847 - accuracy: 0.9757
Epoch 7/15
 - 2s - loss: 0.0713 - accuracy: 0.9799
Epoch 8/15
 - 2s - loss: 0.0611 - accuracy: 0.9830
Epoch 9/15
 - 2s - loss: 0.0521 - accuracy: 0.9855
Epoch 10/15
 - 2s - loss: 0.0452 - accuracy: 0.9880
Epoch 11/15
 - 2s - loss: 0.0386 - accuracy: 0.9904
Epoch 12/15
 - 2s - loss: 0.0329 - accuracy: 0.9920
Epoch 13/15
 - 2s - loss: 0.0283 - accuracy: 0.9937
Epoch 14/15
 - 2s - loss: 0.0240 - accuracy: 0.9952
Epoch 15/15
 - 2s - loss: 0.0208 - accuracy: 0.9960
Epoch 1/15
 - 2s - lo

 - 2s - loss: 0.0831 - accuracy: 0.9766
Epoch 7/20
 - 2s - loss: 0.0703 - accuracy: 0.9805
Epoch 8/20
 - 2s - loss: 0.0597 - accuracy: 0.9838
Epoch 9/20
 - 2s - loss: 0.0509 - accuracy: 0.9862
Epoch 10/20
 - 2s - loss: 0.0440 - accuracy: 0.9884
Epoch 11/20
 - 2s - loss: 0.0379 - accuracy: 0.9907
Epoch 12/20
 - 2s - loss: 0.0325 - accuracy: 0.9922
Epoch 13/20
 - 2s - loss: 0.0282 - accuracy: 0.9937
Epoch 14/20
 - 2s - loss: 0.0243 - accuracy: 0.9946
Epoch 15/20
 - 2s - loss: 0.0206 - accuracy: 0.9957
Epoch 16/20
 - 2s - loss: 0.0177 - accuracy: 0.9966
Epoch 17/20
 - 2s - loss: 0.0151 - accuracy: 0.9977
Epoch 18/20
 - 2s - loss: 0.0127 - accuracy: 0.9982
Epoch 19/20
 - 2s - loss: 0.0109 - accuracy: 0.9984
Epoch 20/20
 - 2s - loss: 0.0094 - accuracy: 0.9989
Epoch 1/20
 - 2s - loss: 0.4274 - accuracy: 0.8911
Epoch 2/20
 - 2s - loss: 0.2089 - accuracy: 0.9408
Epoch 3/20
 - 2s - loss: 0.1554 - accuracy: 0.9557
Epoch 4/20
 - 2s - loss: 0.1231 - accuracy: 0.9640
Epoch 5/20
 - 2s - loss: 0.1000

Epoch 6/10
 - 1s - loss: 0.1059 - accuracy: 0.9701
Epoch 7/10
 - 1s - loss: 0.0913 - accuracy: 0.9747
Epoch 8/10
 - 1s - loss: 0.0798 - accuracy: 0.9778
Epoch 9/10
 - 1s - loss: 0.0701 - accuracy: 0.9809
Epoch 10/10
 - 1s - loss: 0.0619 - accuracy: 0.9832
Epoch 1/10
 - 1s - loss: 0.4918 - accuracy: 0.8785
Epoch 2/10
 - 2s - loss: 0.2343 - accuracy: 0.9335
Epoch 3/10
 - 1s - loss: 0.1809 - accuracy: 0.9478
Epoch 4/10
 - 1s - loss: 0.1470 - accuracy: 0.9579
Epoch 5/10
 - 2s - loss: 0.1230 - accuracy: 0.9648
Epoch 6/10
 - 2s - loss: 0.1054 - accuracy: 0.9695
Epoch 7/10
 - 2s - loss: 0.0905 - accuracy: 0.9741
Epoch 8/10
 - 2s - loss: 0.0795 - accuracy: 0.9778
Epoch 9/10
 - 2s - loss: 0.0692 - accuracy: 0.9809
Epoch 10/10
 - 2s - loss: 0.0609 - accuracy: 0.9831
Epoch 1/10
 - 2s - loss: 0.4840 - accuracy: 0.8807
Epoch 2/10
 - 1s - loss: 0.2345 - accuracy: 0.9334
Epoch 3/10
 - 1s - loss: 0.1816 - accuracy: 0.9488
Epoch 4/10
 - 2s - loss: 0.1487 - accuracy: 0.9572
Epoch 5/10
 - 1s - loss: 0.12

Epoch 11/15
 - 2s - loss: 0.0551 - accuracy: 0.9851
Epoch 12/15
 - 2s - loss: 0.0488 - accuracy: 0.9867
Epoch 13/15
 - 2s - loss: 0.0433 - accuracy: 0.9890
Epoch 14/15
 - 2s - loss: 0.0379 - accuracy: 0.9907
Epoch 15/15
 - 2s - loss: 0.0339 - accuracy: 0.9918
Epoch 1/15
 - 2s - loss: 0.4897 - accuracy: 0.8783
Epoch 2/15
 - 2s - loss: 0.2346 - accuracy: 0.9334
Epoch 3/15
 - 2s - loss: 0.1810 - accuracy: 0.9478
Epoch 4/15
 - 2s - loss: 0.1467 - accuracy: 0.9576
Epoch 5/15
 - 2s - loss: 0.1227 - accuracy: 0.9649
Epoch 6/15
 - 2s - loss: 0.1042 - accuracy: 0.9700
Epoch 7/15
 - 2s - loss: 0.0898 - accuracy: 0.9751
Epoch 8/15
 - 2s - loss: 0.0783 - accuracy: 0.9777
Epoch 9/15
 - 2s - loss: 0.0682 - accuracy: 0.9814
Epoch 10/15
 - 2s - loss: 0.0600 - accuracy: 0.9836
Epoch 11/15
 - 2s - loss: 0.0529 - accuracy: 0.9859
Epoch 12/15
 - 2s - loss: 0.0467 - accuracy: 0.9879
Epoch 13/15
 - 2s - loss: 0.0412 - accuracy: 0.9899
Epoch 14/15
 - 2s - loss: 0.0365 - accuracy: 0.9913
Epoch 15/15
 - 2s - l

 - 2s - loss: 0.0312 - accuracy: 0.9930
Epoch 16/20
 - 2s - loss: 0.0273 - accuracy: 0.9944
Epoch 17/20
 - 2s - loss: 0.0240 - accuracy: 0.9953
Epoch 18/20
 - 2s - loss: 0.0211 - accuracy: 0.9963
Epoch 19/20
 - 2s - loss: 0.0183 - accuracy: 0.9971
Epoch 20/20
 - 2s - loss: 0.0161 - accuracy: 0.9975
Epoch 1/20
 - 2s - loss: 0.4902 - accuracy: 0.8790
Epoch 2/20
 - 2s - loss: 0.2332 - accuracy: 0.9336
Epoch 3/20
 - 2s - loss: 0.1813 - accuracy: 0.9480
Epoch 4/20
 - 2s - loss: 0.1489 - accuracy: 0.9572
Epoch 5/20
 - 2s - loss: 0.1250 - accuracy: 0.9649
Epoch 6/20
 - 2s - loss: 0.1067 - accuracy: 0.9699
Epoch 7/20
 - 2s - loss: 0.0927 - accuracy: 0.9739
Epoch 8/20
 - 2s - loss: 0.0802 - accuracy: 0.9782
Epoch 9/20
 - 2s - loss: 0.0706 - accuracy: 0.9804
Epoch 10/20
 - 2s - loss: 0.0623 - accuracy: 0.9830
Epoch 11/20
 - 2s - loss: 0.0552 - accuracy: 0.9845
Epoch 12/20
 - 2s - loss: 0.0486 - accuracy: 0.9870
Epoch 13/20
 - 2s - loss: 0.0433 - accuracy: 0.9889
Epoch 14/20
 - 2s - loss: 0.0381 

Epoch 5/10
 - 1s - loss: 0.1613 - accuracy: 0.9534
Epoch 6/10
 - 1s - loss: 0.1410 - accuracy: 0.9594
Epoch 7/10
 - 1s - loss: 0.1245 - accuracy: 0.9644
Epoch 8/10
 - 1s - loss: 0.1109 - accuracy: 0.9681
Epoch 9/10
 - 1s - loss: 0.0993 - accuracy: 0.9717
Epoch 10/10
 - 1s - loss: 0.0897 - accuracy: 0.9751
Epoch 1/10
 - 2s - loss: 0.6044 - accuracy: 0.8617
Epoch 2/10
 - 1s - loss: 0.2769 - accuracy: 0.9229
Epoch 3/10
 - 1s - loss: 0.2195 - accuracy: 0.9384
Epoch 4/10
 - 1s - loss: 0.1836 - accuracy: 0.9478
Epoch 5/10
 - 1s - loss: 0.1585 - accuracy: 0.9557
Epoch 6/10
 - 1s - loss: 0.1383 - accuracy: 0.9610
Epoch 7/10
 - 1s - loss: 0.1226 - accuracy: 0.9654
Epoch 8/10
 - 1s - loss: 0.1091 - accuracy: 0.9691
Epoch 9/10
 - 1s - loss: 0.0979 - accuracy: 0.9718
Epoch 10/10
 - 1s - loss: 0.0883 - accuracy: 0.9752
Epoch 1/10
 - 2s - loss: 0.6140 - accuracy: 0.8561
Epoch 2/10
 - 1s - loss: 0.2786 - accuracy: 0.9223
Epoch 3/10
 - 1s - loss: 0.2204 - accuracy: 0.9383
Epoch 4/10
 - 1s - loss: 0.18

Epoch 10/15
 - 2s - loss: 0.0845 - accuracy: 0.9766
Epoch 11/15
 - 2s - loss: 0.0764 - accuracy: 0.9792
Epoch 12/15
 - 2s - loss: 0.0693 - accuracy: 0.9817
Epoch 13/15
 - 1s - loss: 0.0626 - accuracy: 0.9837
Epoch 14/15
 - 1s - loss: 0.0566 - accuracy: 0.9855
Epoch 15/15
 - 1s - loss: 0.0520 - accuracy: 0.9865
Epoch 1/15
 - 2s - loss: 0.6153 - accuracy: 0.8559
Epoch 2/15
 - 1s - loss: 0.2795 - accuracy: 0.9222
Epoch 3/15
 - 1s - loss: 0.2227 - accuracy: 0.9372
Epoch 4/15
 - 1s - loss: 0.1875 - accuracy: 0.9467
Epoch 5/15
 - 1s - loss: 0.1623 - accuracy: 0.9537
Epoch 6/15
 - 1s - loss: 0.1430 - accuracy: 0.9594
Epoch 7/15
 - 1s - loss: 0.1268 - accuracy: 0.9644
Epoch 8/15
 - 1s - loss: 0.1128 - accuracy: 0.9684
Epoch 9/15
 - 1s - loss: 0.1016 - accuracy: 0.9714
Epoch 10/15
 - 1s - loss: 0.0917 - accuracy: 0.9746
Epoch 11/15
 - 1s - loss: 0.0830 - accuracy: 0.9773
Epoch 12/15
 - 1s - loss: 0.0757 - accuracy: 0.9794
Epoch 13/15
 - 1s - loss: 0.0685 - accuracy: 0.9817
Epoch 14/15
 - 1s - l

Epoch 4/20
 - 2s - loss: 0.1846 - accuracy: 0.9478
Epoch 5/20
 - 2s - loss: 0.1597 - accuracy: 0.9552
Epoch 6/20
 - 2s - loss: 0.1395 - accuracy: 0.9614
Epoch 7/20
 - 2s - loss: 0.1236 - accuracy: 0.9655
Epoch 8/20
 - 2s - loss: 0.1109 - accuracy: 0.9685
Epoch 9/20
 - 2s - loss: 0.0996 - accuracy: 0.9726
Epoch 10/20
 - 2s - loss: 0.0895 - accuracy: 0.9749
Epoch 11/20
 - 2s - loss: 0.0808 - accuracy: 0.9778
Epoch 12/20
 - 2s - loss: 0.0733 - accuracy: 0.9799
Epoch 13/20
 - 2s - loss: 0.0667 - accuracy: 0.9818
Epoch 14/20
 - 2s - loss: 0.0605 - accuracy: 0.9838
Epoch 15/20
 - 2s - loss: 0.0549 - accuracy: 0.9858
Epoch 16/20
 - 2s - loss: 0.0506 - accuracy: 0.9866
Epoch 17/20
 - 2s - loss: 0.0458 - accuracy: 0.9885
Epoch 18/20
 - 2s - loss: 0.0416 - accuracy: 0.9898
Epoch 19/20
 - 2s - loss: 0.0380 - accuracy: 0.9910
Epoch 20/20
 - 2s - loss: 0.0347 - accuracy: 0.9921
Epoch 1/20
 - 2s - loss: 0.6201 - accuracy: 0.8548
Epoch 2/20
 - 2s - loss: 0.2781 - accuracy: 0.9235
Epoch 3/20
 - 2s - l

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=<keras.wrappers.scikit_learn.KerasClassifier object at 0x00000167D9727D68>,
             iid='warn', n_jobs=None,
             param_grid={'batch_size': [30, 50, 100], 'epochs': [10, 15, 20]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_log_loss', verbose=0)

In [68]:
#7
best_model = grid.best_estimator_.model

In [20]:
grid.best_params_

{'batch_size': 50, 'epochs': 20}

In [23]:
#8
batch_size = [50]
epochs = [20]
param_grid = dict(batch_size=batch_size, epochs=epochs)
grid_test = GridSearchCV(estimator = model, param_grid = param_grid, cv = 10, scoring = 'neg_log_loss')

In [26]:
grid_test.fit(X_test, y_test)

Epoch 1/20
 - 2s - loss: 1.1646 - accuracy: 0.7366
Epoch 2/20
 - 1s - loss: 0.4925 - accuracy: 0.8870
Epoch 3/20
 - 1s - loss: 0.3641 - accuracy: 0.9082
Epoch 4/20
 - 1s - loss: 0.3032 - accuracy: 0.9198
Epoch 5/20
 - 1s - loss: 0.2679 - accuracy: 0.9263
Epoch 6/20
 - 1s - loss: 0.2402 - accuracy: 0.9329
Epoch 7/20
 - 1s - loss: 0.2177 - accuracy: 0.9408
Epoch 8/20
 - 1s - loss: 0.1990 - accuracy: 0.9459
Epoch 9/20
 - 1s - loss: 0.1820 - accuracy: 0.9513
Epoch 10/20
 - 1s - loss: 0.1678 - accuracy: 0.9550
Epoch 11/20
 - 1s - loss: 0.1544 - accuracy: 0.9584
Epoch 12/20
 - 1s - loss: 0.1422 - accuracy: 0.9611
Epoch 13/20
 - 1s - loss: 0.1310 - accuracy: 0.9666
Epoch 14/20
 - 1s - loss: 0.1219 - accuracy: 0.9678
Epoch 15/20
 - 1s - loss: 0.1116 - accuracy: 0.9720
Epoch 16/20
 - 1s - loss: 0.1046 - accuracy: 0.9740
Epoch 17/20
 - 1s - loss: 0.0952 - accuracy: 0.9751
Epoch 18/20
 - 1s - loss: 0.0879 - accuracy: 0.9788
Epoch 19/20
 - 1s - loss: 0.0818 - accuracy: 0.9799
Epoch 20/20
 - 1s - l

Epoch 20/20
 - 1s - loss: 0.0751 - accuracy: 0.9831
Epoch 1/20
 - 2s - loss: 1.0757 - accuracy: 0.7644
Epoch 2/20
 - 1s - loss: 0.4911 - accuracy: 0.8849
Epoch 3/20
 - 1s - loss: 0.3709 - accuracy: 0.9038
Epoch 4/20
 - 1s - loss: 0.3126 - accuracy: 0.9167
Epoch 5/20
 - 1s - loss: 0.2741 - accuracy: 0.9257
Epoch 6/20
 - 1s - loss: 0.2452 - accuracy: 0.9339
Epoch 7/20
 - 1s - loss: 0.2218 - accuracy: 0.9383
Epoch 8/20
 - 1s - loss: 0.2018 - accuracy: 0.9441
Epoch 9/20
 - 1s - loss: 0.1857 - accuracy: 0.9491
Epoch 10/20
 - 1s - loss: 0.1689 - accuracy: 0.9546
Epoch 11/20
 - 1s - loss: 0.1556 - accuracy: 0.9579
Epoch 12/20
 - 1s - loss: 0.1435 - accuracy: 0.9612
Epoch 13/20
 - 1s - loss: 0.1311 - accuracy: 0.9663
Epoch 14/20
 - 1s - loss: 0.1207 - accuracy: 0.9670
Epoch 15/20
 - 1s - loss: 0.1120 - accuracy: 0.9713
Epoch 16/20
 - 1s - loss: 0.1018 - accuracy: 0.9747
Epoch 17/20
 - 1s - loss: 0.0938 - accuracy: 0.9769
Epoch 18/20
 - 1s - loss: 0.0865 - accuracy: 0.9788
Epoch 19/20
 - 1s - l

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=<keras.wrappers.scikit_learn.KerasClassifier object at 0x00000167D9727D68>,
             iid='warn', n_jobs=None,
             param_grid={'batch_size': [50], 'epochs': [20]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_log_loss', verbose=0)

In [49]:
best_model_test = grid_test.best_estimator_.model

In [58]:
y_predict = grid.best_estimator_.model.predict(X_test)

In [59]:
print(y_predict.shape)

(10000, 10)


In [64]:
score = grid.best_estimator_.model.evaluate(X_test, y_test, verbose = 1)

10000/10000 [==============================] - 1s 86us/step


In [65]:
print(score[1])

0.9957000017166138


In [66]:
print("Our prediction accuracy is 0.9957000017166138")

Our prediction accuracy is 0.9957000017166138
